[package]
name = "lan-port-scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.29", features = ["derive"] }
default-net = "0.22.0"
ipnetwork = "0.21.1"
itertools = "0.14.0"
tokio = { version = "1.43.0", features = ["full"] }
